# Generated by Django 6.0.5 on 2026-05-25 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TodoItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(max_length=400, verbose_name='description')),
                ('status', models.CharField(verbose_name='status')),
                ('date', models.DateField(verbose_name='date')),
            ],
        ),
    ]
