# Generated by Django 6.0.5 on 2026-07-04 10:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_title', models.TextField(max_length=200, verbose_name='Заголовок статуса')),
            ],
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_title', models.TextField(max_length=200, verbose_name='Заголовок типа')),
            ],
        ),
        migrations.CreateModel(
            name='TodoItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(max_length=200, verbose_name='Заголовок')),
                ('description', models.TextField(blank=True, max_length=500, null=True, verbose_name='Описание')),
                ('date_of_add', models.DateField(auto_now_add=True, verbose_name='Дата создания')),
                ('date_of_update', models.DateField(auto_now=True, verbose_name='Последние изменения')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task', to='todo_app.status', verbose_name='Статус')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task', to='todo_app.type', verbose_name='Тип')),
            ],
            options={
                'verbose_name': 'task',
                'db_table': 'Task',
            },
        ),
    ]
