# Generated by Django 6.0.5 on 2026-05-25 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='todoitem',
            options={'verbose_name': 'task'},
        ),
        migrations.AlterField(
            model_name='todoitem',
            name='date',
            field=models.DateField(auto_now=True, verbose_name='date'),
        ),
        migrations.AlterModelTable(
            name='todoitem',
            table='task',
        ),
    ]
