# Generated by Django 6.0.5 on 2026-07-04 11:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('todo_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todoitem',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='task',
                                    to='todo_app.status', verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='todoitem',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='task',
                                    to='todo_app.type', verbose_name='Тип'),
        ),
    ]
