# Generated by Django 6.0.5 on 2026-07-05 11:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('todo_app', '0002_alter_todoitem_status_alter_todoitem_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todoitem',
            name='type',
        ),
        migrations.AddField(
            model_name='todoitem',
            name='type',
            field=models.ManyToManyField(blank=True, related_name='tasks', to='todo_app.type', verbose_name='Типы'),
        ),
    ]
