# Generated by Django 6.0.5 on 2026-05-31 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0002_alter_todoitem_options_alter_todoitem_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todoitem',
            name='date',
            field=models.DateField(blank=True, null=True, verbose_name='date'),
        ),
    ]
