# Generated by Django 6.0.5 on 2026-06-03 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0003_alter_todoitem_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todoitem',
            name='status',
            field=models.CharField(choices=[('new', 'новая'), ('in_progress', 'в процессе'), ('done', 'сделано')], max_length=30, verbose_name='status'),
        ),
    ]
