# Generated by Django 6.0.5 on 2026-07-05 12:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('todo_app', '0003_remove_todoitem_type_todoitem_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todoitem',
            name='type',
            field=models.ManyToManyField(blank=True, null=True, related_name='tasks', to='todo_app.type',
                                         verbose_name='Типы'),
        ),
    ]
