# Generated by Django 6.0.5 on 2026-07-16 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0004_alter_todoitem_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('begining_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('project_title', models.CharField(max_length=200)),
                ('project_description', models.TextField(max_length=500)),
            ],
        ),
        migrations.AlterField(
            model_name='todoitem',
            name='type',
            field=models.ManyToManyField(blank=True, related_name='tasks', to='todo_app.type', verbose_name='Типы'),
        ),
    ]
