# Generated by Django 6.0.5 on 2026-06-03 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0004_alter_todoitem_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='todoitem',
            name='detail_description',
            field=models.TextField(blank=True, max_length=400, null=True, verbose_name='detail_description'),
        ),
    ]
