# Generated by Django 6.0.5 on 2026-06-03 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0005_todoitem_detail_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todoitem',
            name='description',
            field=models.TextField(max_length=200, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='todoitem',
            name='detail_description',
            field=models.TextField(blank=True, max_length=600, null=True, verbose_name='detail_description'),
        ),
    ]
