# Generated by Django 6.0.5 on 2026-07-16 21:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0005_project_alter_todoitem_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'verbose_name': 'project'},
        ),
        migrations.AddField(
            model_name='todoitem',
            name='project',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.RESTRICT, related_name='project', to='todo_app.project', verbose_name='Статус'),
        ),
        migrations.AlterModelTable(
            name='project',
            table='Project',
        ),
    ]
