# Generated by Django 6.0.5 on 2026-06-06 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0006_alter_todoitem_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todoitem',
            name='description',
            field=models.CharField(max_length=200, verbose_name='description'),
        ),
    ]
