# Generated by Django 6.0.5 on 2026-07-16 23:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0006_alter_project_options_todoitem_project_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todoitem',
            name='project',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.RESTRICT, related_name='project', to='todo_app.project', verbose_name='Проект'),
        ),
    ]
