# Generated by Django 6.0.5 on 2026-07-23 21:35

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0009_alter_todoitem_project'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='members',
            field=models.ManyToManyField(related_name='Project', to=settings.AUTH_USER_MODEL, verbose_name='Участники'),
        ),
    ]
